# Generated by Django 4.1.1 on 2022-10-25 15:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "place_id",
                    models.CharField(
                        blank=True, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("place_name", models.CharField(blank=True, max_length=100)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("category_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address_name", models.CharField(blank=True, max_length=100)),
                ("road_address_name", models.CharField(blank=True, max_length=100)),
                ("place_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("search_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "departure",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                (
                    "destination",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("keyword", models.CharField(max_length=20)),
                ("search_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
