# Generated by Django 4.1.1 on 2022-10-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsonmypath", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="place", name="x", field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="place", name="y", field=models.FloatField(default=0.0),
        ),
    ]
